#!/bin/sh

set -e

case "${1}" in
  configure)
    if [ -z "$2" ]; then
      raspi-config nonint do_wayland W1
      raspi-config nonint do_boot_behaviour B4
      update-desktop-database /usr/share/raspi-ui-overrides/applications/
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`${1}'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
